version: "3.7"

services:

  ui:
    image: javalisson/pizzaria-pedidos-ui:0.1
    command: ""
    build:
      context: ./ui
      target: production
    ports: 
      - "80:80"
    environment:
      NODE_ENV: production

  core:
    image: javalisson/pizzaria-pedidos-core:0.1
    command: npm run start
    restart: always
    environment:
      NODE_ENV: production